pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Emmanuel-Ebiwari/alx-backend-python.git',
                        credentialsId: 'github-token'
                    ]]
                ]
                sh 'git branch'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                source venv/bin/activate
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
