pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'emmanuelhub/messaging-app:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Emmanuel-Ebiwari/alx-backend-python.git',
                        credentialsId: 'github-credential'
                    ]]
                ]
                sh 'git branch'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                source venv/bin/activate
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                source venv/bin/activate
                pytest messaging_app/ --junitxml=report.xml
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd messaging_app
                docker build -t $DOCKER_IMAGE .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }

        stage('Publish Report') {
            steps {
                echo 'Preparing test report...'
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }
}
