pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'git branch'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                python3 -m venv venv
                source messaging_app/venv/bin/activate
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }
}
