pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/Emmanuel-Ebiwari/alx-backend-python/tree/main/messaging_app', branch: 'main'
            }
        }

        stage('Set up Python') {
            steps {
                sh '''
                python3 -m venv venv
                source venv/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source venv/bin/activate
                pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
